// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkd1cDXpGZn3oedZ-dTC1QiIIzjJCJCjc',
    appId: '1:570294912099:web:4e098531f4c4ef186ba456',
    messagingSenderId: '570294912099',
    projectId: 'smart-parking-5d33c',
    authDomain: 'smart-parking-5d33c.firebaseapp.com',
    databaseURL: 'https://smart-parking-5d33c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-parking-5d33c.appspot.com',
    measurementId: 'G-LDNCSVP604',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2KF2-4dvAoThrEC2KLVZBzU_Y7TLEf_U',
    appId: '1:570294912099:android:46211ee874d3404d6ba456',
    messagingSenderId: '570294912099',
    projectId: 'smart-parking-5d33c',
    databaseURL: 'https://smart-parking-5d33c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-parking-5d33c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4JhBtPQw4Cfr3RoiE08p9q-2s0qgOdJc',
    appId: '1:570294912099:ios:90870f41b7824f766ba456',
    messagingSenderId: '570294912099',
    projectId: 'smart-parking-5d33c',
    databaseURL: 'https://smart-parking-5d33c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-parking-5d33c.appspot.com',
    iosBundleId: 'com.example.smartParking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4JhBtPQw4Cfr3RoiE08p9q-2s0qgOdJc',
    appId: '1:570294912099:ios:90870f41b7824f766ba456',
    messagingSenderId: '570294912099',
    projectId: 'smart-parking-5d33c',
    databaseURL: 'https://smart-parking-5d33c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-parking-5d33c.appspot.com',
    iosBundleId: 'com.example.smartParking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkd1cDXpGZn3oedZ-dTC1QiIIzjJCJCjc',
    appId: '1:570294912099:web:c7df4be04a38ec446ba456',
    messagingSenderId: '570294912099',
    projectId: 'smart-parking-5d33c',
    authDomain: 'smart-parking-5d33c.firebaseapp.com',
    databaseURL: 'https://smart-parking-5d33c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-parking-5d33c.appspot.com',
    measurementId: 'G-J1ZG0W9E89',
  );

}